server:
  port: ${PORT:8080}
  forward-headers-strategy: framework

spring:
  application:
    name: remember-me-api

  datasource:
    url: postgresql://remember_me_user:zv3pfTZyXSmkn0tfWBPGyAxvNFXwSgJS@dpg-db2930rncjis73drf110-a/remember_me_db_veac
    username: remember_me_user
    password: zv3pfTZyXSmkn0tfWBPGyAxvNFXwSgJS
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

app:
  admin:
    create-test-admin: ${CREATE_TEST_ADMIN:false}
