server:
  port: ${PORT:8080}
  forward-headers-strategy: framework

spring:
  application:
    name: remember-me-api

  datasource:
    url: ${SPRING_DATASOURCE_URL:${DATABASE_URL:jdbc:postgresql://dpg-db2930rncjis73drf110-a.oregon-postgres.render.com/remember_me_db_veac?sslmode=require}}
    username: ${SPRING_DATASOURCE_USERNAME:remember_me_user}
    password: ${SPRING_DATASOURCE_PASSWORD:zv3pfTZyXSmkn0tfWBPGyAxvNFXwSgJS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

app:
  admin:
    create-test-admin: ${CREATE_TEST_ADMIN:false}
