package com.rememberme.api.dto.request;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import lombok.Data;

@Data
@Schema(description = "FCM token generated by the Flutter application's Firebase Messaging client")
public class FcmTokenRequest {

    @NotBlank(message = "FCM token is required")
    @Schema(description = "Firebase Cloud Messaging registration token", example = "FCM_TOKEN", requiredMode = Schema.RequiredMode.REQUIRED)
    private String fcmToken;
}
